server:
  port: 8082

spring:
  datasource:
    username: root
    url: jdbc:mysql://localhost:3306/boppo_tech
    driverClassName: com.mysql.jdbc.Driver
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: 'true'
